### ISSUE TITLE
unRAID docker container doesn't have gui option

### ISSUE THREAD

**Issue by doctorevil30564** [kmcgill88/k-plex#1]
I wanted to ask if it would be possible for you to create a specific version of k-plex to run on unRAID.

I tried to let it convert the image but found out the hard way that when I click the icon for it, it doesn't give me a gui option like my regular plex docker container did. I also had to add the variables in for the library path and the /config path manually.

I am able to get to the gui by typing in the ip address and port number, so it isn't a huge issue, but wanted to report it. None of the available unRAID specific plex docker images have comskip built into them like yours does.

**Comment by kmcgill88** [comment]
Hi @doctorevil30564, 

I don't use unRAID myself so I wouldn't be a good resource on the topic. I did take a quick look and saw the official container has some [XML](https://github.com/plexinc/pms-docker/blob/master/plex-unRAID.xml). I'm happy to accept PR's if you come up with a good solution for unRAID and want to add it here.

**Comment by doctorevil30564** [comment]
I found a solution to get it working. Basically I had to install a
different container then find the my-plex.xml file for it, then change the
repo to your repo, then change the /config line to point to where my k-plex
container had it. I am not at home at the moment, but I believe the other
container was the Linuxserver one.

**Comment by kmcgill88** [comment]
Awesome! Glad you got it working, thanks for sharing.
